import "app/globals.css";
import Nav from "../components/nav";
import { Auth } from "../components/auth";

export const metadata = {
  title: "Stock App by FMJ",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />

        {children}
      </body>
    </html>
  );
}
